version: '3'

services:
  storm: &storm
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    # command: ["storm", "model-check", "models/markov-chain.pm"]
    entrypoint: storm

  shell: &shell
    <<: *storm
    entrypoint: bash
    stdin_open: true
    tty: true

  stormpy: &stormpy
    <<: *shell
    command: >-
      -x -c "ipython -i -c 'import stormpy; print(stormpy.__version__)'"
